spring:
  profiles:
    include: development
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbs:
          batch_size: 30
        order_inserts: true
        order_updates: true
